[pen_config.Emott]
layers = [
    { layer_id = 1, name = "Iris Purple 49", color = "#7b5198", pen_width = "1.0mm" },
    { layer_id = 2, name = "Light Pink 51", color = "#ce84af", pen_width = "1.0mm" },
    { layer_id = 3, name = "Saxe Blue 79", color = "#607184", pen_width = "1.0mm" },
    { layer_id = 4, name = "Emerald Green 31", color = "#57c070", pen_width = "1.0mm" },
    { layer_id = 5, name = "Light Green 5", color = "#a2ce5a", pen_width = "1.0mm" },
    { layer_id = 6, name = "Pine Green 77", color = "#22341c", pen_width = "1.0mm" },
    { layer_id = 7, name = "Violet 12", color = "#7b5dda", pen_width = "1.0mm" },
    { layer_id = 8, name = "Lilac 34", color = "#be98c0", pen_width = "1.0mm" },
    { layer_id = 9, name = "Mauve 80", color = "#341c3d", pen_width = "1.0mm" },
    { layer_id = 10, name = "Light Blue 8", color = "#42cbf0", pen_width = "1.0mm" },
    { layer_id = 11, name = "Yellow 2", color = "#c3b145", pen_width = "1.0mm" },
    { layer_id = 12, name = "Coral Pink 66", color = "#91443e", pen_width = "1.0mm" },
    { layer_id = 13, name = "Red Wine 60", color = "#23101b", pen_width = "1.0mm" },
    { layer_id = 14, name = "Blue Green 39", color = "#1a2128", pen_width = "1.0mm" },
    { layer_id = 15, name = "Lemon 28", color = "#cece4f", pen_width = "1.0mm" },
    { layer_id = 16, name = "Grey 37", color = "#7c7c7c", pen_width = "1.0mm" },
    { layer_id = 17, name = "Amethyst 35", color = "#1c0f1f", pen_width = "1.0mm" },
    { layer_id = 18, name = "Dark Yellow 19", color = "#3a361b", pen_width = "1.0mm" },
    { layer_id = 19, name = "Straw Yellow 73", color = "#958834", pen_width = "1.0mm" },
    { layer_id = 20, name = "Blue 33", color = "#3263bf", pen_width = "1.0mm" },
    { layer_id = 21, name = "Fuchsia 11", color = "#2b1741", pen_width = "1.0mm" },
    { layer_id = 22, name = "Orange 4", color = "#d38f37", pen_width = "1.0mm" },
    { layer_id = 23, name = "Sky Blue 48", color = "#83c7e6", pen_width = "1.0mm" },
    { layer_id = 24, name = "Light Violet 63", color = "#6256a3", pen_width = "1.0mm" },
    { layer_id = 25, name = "Red 15", color = "#f40f18", pen_width = "1.0mm" },
    { layer_id = 26, name = "Bright Yellow 3", color = "#ffff32", pen_width = "1.0mm" },
    { layer_id = 27, name = "Khaki Green 7", color = "#121c13", pen_width = "1.0mm" },
    { layer_id = 28, name = "Green 6", color = "#84d84d", pen_width = "1.0mm" },
    { layer_id = 29, name = "Turquoise 71", color = "#516f89", pen_width = "1.0mm" },
    { layer_id = 30, name = "Beige 45", color = "#f5f5dd", pen_width = "1.0mm" },
    { layer_id = 31, name = "Black 24", color = "#0d0d0d", pen_width = "1.0mm" },
    { layer_id = 32, name = "Pink 13", color = "#d62654", pen_width = "1.0mm" },
    { layer_id = 33, name = "Dark Brown 22", color = "#615e5b", pen_width = "1.0mm" },
    { layer_id = 34, name = "Pure Pink 67", color = "#6b3464", pen_width = "1.0mm" },
    { layer_id = 35, name = "Brown 21", color = "#261a0f", pen_width = "1.0mm" },
    { layer_id = 36, name = "Vermillon 16", color = "#853a27", pen_width = "1.0mm" },
    { layer_id = 37, name = "Baby Pink 68", color = "#eec7c2", pen_width = "1.0mm" },
    { layer_id = 38, name = "Light Orange 54", color = "#c69f66", pen_width = "1.0mm" },
    { layer_id = 39, name = "Apple Green 72", color = "#829238", pen_width = "1.0mm" },
    { layer_id = 40, name = "Sea Fog 81", color = "#83869b", pen_width = "1.0mm" },
]
